plotwitherror: further generalise plotting of asymmetric errors to support data sets where different points have different numbers of error bars (negative and positive error sets can differ to) by introducing some logic to calculate the length of the arrowhead lines based on the number of non-zero errors encountered this way, data points with fewer errors are simply equipped with errors of value "0" to generate consistent error arrays for all point in a plot while keeping sane arrowhead line lengths